---
- name: Install Rancher Desktop on Linux
  ansible.builtin.include_tasks: linux.yml
  when: ansible_facts['system'] == 'Linux'

- name: Install Rancher Desktop on macOS
  ansible.builtin.include_tasks: darwin.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Helm
  ansible.builtin.include_tasks: install_helm.yml
  when: install_rancher_server | default(false) | bool

- name: Install Rancher Server on Kubernetes
  ansible.builtin.include_tasks: install_rancher.yml
  when: install_rancher_server | default(false) | bool
